export enum ActionTypes {
  LOAD_CLASSIFIER='davinci/Classifier/LOAD_CLASSIFIER',//yzh
  LOAD_CLASSIFIER_SUCCESS= 'davinci/Classifier/LOAD_CLASSIFIER_SUCCESS',//yzh
  LOAD_CLASSIFIER_FAILURE='davinci/Classifier/LOAD_CLASSIFIER_FAILURE',//yzh
  EDIT_CLASSIFIER_SUCCESS = 'davinci/Classifier/EDIT_CLASSIFIER_SUCCESS',
  UNDO_OPERATION_SUCCESS = 'davinci/Classifier/UNDO_OPERATION_SUCCESS',
  REDO_OPERATION_SUCCESS = 'davinci/Classifier/REDO_OPERATION_SUCCESS',
  START_CLASSIFIER= 'davinci/Classifier/START_CLASSIFIER',
  START_CLSSIFIER_SUCCESS = 'davinci/Classifier/START_CLSSIFIER_SUCCESS',
  CHANGE_TAB_ACTIVE_KEY = 'davinci/Classifier/CHANGE_TAB_ACTIVE_KEY',
  CHANGE_TAB_ACTIVE_KEY_SUCCESS = 'davinci/Classifier/CHANGE_TAB_ACTIVE_KEY_SUCCESS',
  CHANGE_BASIC_LEARNING_MODAL= 'davinci/Classifier/CHANGE_BASIC_LEARNING_MODAL',
  CHANGE_BASIC_LEARNING_MODAL_SUCCESS='davinci/Classifier/CHANGE_BASIC_LEARNING_MODAL_SUCCESS',
  CHANGE_BASIC_LEARNING_INPUTVALUE='davinci/Classifier/CHANGE_BASIC_LEARNING_INPUTVALUE',
  CHANGE_BASIC_LEARNING_INPUTVALUE_SUCCESS='davinci/Classifier/CHANGE_BASIC_LEARNING_INPUTVALUE_SUCCESS',
  CHANGE_INPUT_NUMBER='davinci/Classifier/CHANGE_INPUT_NUMBER',
  CHANGE_INPUT_NUMBER_SUCCESS='davinci/Classifier/CHANGE_INPUT_NUMBER_SUCCESS',
  HANDLE_PERIODI_CITY='davinci/Classifier/HANDLE_PERIODI_CITY',
  HANDLE_PERIODI_CITY_SUCCESS='davinci/Classifier/HANDLE_PERIODI_CITY_SUCCESS'
}
