export enum ActionTypes {
  LOAD_FORECASTING='davinci/Forecast/LOAD_FORECASTING',//yzh
  LOAD_FORECASTING_SUCCESS= 'davinci/Forecast/LOAD_FORECASTING_SUCCESS',//yzh
  LOAD_FORECASTING_FAILURE='davinci/Forecast/LOAD_FORECASTING_FAILURE',//yzh
  EDIT_FORECASTING_SUCCESS = 'davinci/Forecast/EDIT_FORECASTING_SUCCESS',
  UNDO_OPERATION_SUCCESS = 'davinci/Forecast/UNDO_OPERATION_SUCCESS',
  REDO_OPERATION_SUCCESS = 'davinci/Forecast/REDO_OPERATION_SUCCESS',
  startClassifierData = 'davinci/Forecast/startClassifierData',
  START_CLSSIFIER_DATA_SUCCESS = 'davinci/Forecast/START_CLSSIFIER_DATA_SUCCESS'
}
